create table sites (
  id bigint generated by default as identity primary key,
  url text not null,
  status text not null default 'UNKNOWN',
  status_code integer,
  latency_ms integer,
  last_checked timestamptz,
  failure_count integer not null default 0,
  incident boolean not null default false,
  created_at timestamptz not null default now()
);
